### ISSUE TITLE
Case sensitivity issues on windows

### ISSUE THREAD

**Issue by TomKemperNL** [TypeStrong/tsify#212]
As a first-timer I was trying to get the whole react with typescript and browserify pipe working and ran into some issues.

Working on windows-10 I navigated to my source directory:
D:\Dev\react\helloworld\src
however, I did this by navigating on the command line to
D:\dev\react\helloworld\src
Windows, being a case-insensitive file-system, did not really mind.

I then started getting the error:
Error: tsify: no compiled file for D:\dev\react\helloworld\src\index.tsx

I then noticed that it logged:
Cache read D:/__tsify__/dev/react/helloworld/src/index.jsx
Cache miss on D:/__tsify__/dev/react/helloworld/src/index.jsx
But the cache contained
D:/__tsify__/Dev/react/helloworld/src/index.jsx

There are now (at least) 2 odd things:
1) if I log Host/this.caseSensitive it returns true, whereas I'm pretty sure windows-10 is still case insensitive
2) if I run the exact same command when I navigate to the same directory, but use the proper capitalization when navigating (so I cd into Dev instead of dev), the error is resolved... So it seems tsify is getting it's info from a non-canonicalized 'current working directory' somewhere.

This is probably related to #211, but manually applying that fix did not solve my issues.

(small addendum, the same behavior applies when running through grunt: it works if you navigated to the gruntfile using the exact capitalization, but if you used different capitalization then tsify fails)

**Comment by TomKemperNL** [comment]
I figured I'd take a look and see if I could somehow contribute, so I pulled the repo and ran the tests on my windows machine:
105 out of 200 failed.

Somewhat startled I decided to see if I could maybe try and fix some of that, so I forked it and added an AppVeyor account (Travis, but with a windows machine), since there were 'obviously' issues with windows...

Much to my surprise, when I got that working, all the tests passed...

And lo and behold, I made the same error:
I had cloned tsify into D:\Dev\tsify
I navigated to D:\dev\tsify
and ran npm install, npm run test-main
If I had navigated to D:\Dev\tsify, everything would have passed

**Comment by cartant** [comment]
Thanks for raising the issue. I've only skimmed it, but the strange thing is that I use a Windows machine for most of my development, so I'm not sure how I missed failing tests. I will have a look into this after I've had my first coffee of the day.

**Comment by cartant** [comment]
I've imbibed some coffee and have read your posts.

I'm not using Windows 10 and I'm unable to reproduce the behaviour you've described. However, I agree that this is likely related to #211. I'll get that merged soon and hopefully it'll fix this for you.

**Comment by cartant** [comment]
I've merged #211. If you could have a look to see whether it addresses your issue, that would be appreciated.

**Comment by TomKemperNL** [comment]
I'll have a look at it this weekend...

I'm suddenly thinking it may be related to having recently enabled the linux subsystem... (https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)

**Comment by TomKemperNL** [comment]
#211 Didn't fix it, here's a gist of my run: https://gist.github.com/TomKemperNL/47dc4fdf6ea592831094920f7d44e272

Line 39 is when I lose my cap. 

Oh, and plot thickens: the tests run fine on a fresh Win-10 install (node 7.1)

So I guess it's -something- in my environment. If I find the culprit I'll try and create a pull-request

**Comment by cartant** [comment]
Unfortunately, I think this is an bug with Browserify. The interesting bit is this part:

    Error: tsify: no compiled file for D:\dev\frontendklooien\react\helloworld\src\index.tsx

Note the path. That path is what's received from Browserify. You can see that `file` is what's received in the [transform](https://github.com/TypeStrong/tsify/blob/v2.0.2/lib/Tsifier.js#L251) and it's then passed to [`getCompiledFile`](https://github.com/TypeStrong/tsify/blob/v2.0.2/lib/Tsifier.js#L288-L291) as `inputFile`. Neither `file` nor `inputFile` are modified.

I suspect that Browserify is assuming that Windows is a case-insensitive OS and is converting the path to lower case before passing it to the transform.

If you are going to raise an issue with Browserify, this is the [bad practice reference](https://nodejs.org/en/docs/guides/working-with-different-filesystems/) that was included in [a tsify issue](https://github.com/TypeStrong/tsify/issues/200) that was raised re: detecting fs case sensitivity.

**Comment by TomKemperNL** [comment]
Upgrading to Node 7.1.0 fixed it as well. So I'll probably try and figure out what changed where as a node debugging excercise, but the practical issue is apparently already solved waaay upstream.

**Comment by duncanawoods** [comment]
This has been driving me insane. Tsify is creating bundles that fail to initialise but given its something to do with the minimised module init code, I can't decipher why.

Its got something to do with windows path casing but the insane thing is that it seems I have to capitalise the first folder in the path irrespective of its actual case. WTF!

Example directory structure:

    folder1
        jasmine.d.ts
    folder2
        main.ts
        package.json
        node_modules

With a command line that will fail:

    node node_modules/browserify/bin/cmd "..\folder1\jasmine.d.ts" "main.ts" --standalone MyBundle -p [ tsify --noImplicitAny --suppressImplicitAnyIndexErrors --target ES5 --module commonjs ] -o "bundle.js"

But if I capitalise "folder1" (which is not what the system thinks it is), it will create a working bundle:

    node node_modules/browserify/bin/cmd "..\Folder1\jasmine.d.ts" "main.ts" --standalone MyBundle -p [ tsify --noImplicitAny --suppressImplicitAnyIndexErrors --target ES5 --module commonjs ] -o "bundle.js"

If I use absolute paths, I get the same failure based on folder capitalising that folder. If I rename folder1 to Folder2, I see the same behaviour but the demand for a capitalised folder name now happens to match reality.

Versions
 node 7.40
 browserify 13.3
 tsify 3.0

**Comment by duncanawoods** [comment]
Ok, to add the weirdness, it looks like the last path in the file list has to be the correct case so I am having to use a different case for the same path depending on its position in the list...

**Comment by cartant** [comment]
@duncanawoods Do you see an error similar to the one I've highlighted in [this comment](https://github.com/TypeStrong/tsify/issues/212#issuecomment-261086041)? Also, if I supply you with some modifications to the `tsify` source - for additional logging - would you be able to re-run your build and provide me with the output? If so, I'll start looking into this. It is a strange one and no doubt frustrating for you.

**Comment by cartant** [comment]
@duncanawoods @TomKemperNL I've just found and fixed a bug in the case sensitivity detection (that I introduced). There is a new release - 3.0.1 - which should, hopefully, see this issue closed.

**Comment by duncanawoods** [comment]
> There is a new release - 3.0.1 - which should, hopefully, see this issue closed.

Just tried it and I see the same behaviour.

> Do you see an error similar to the one I've highlighted in this comment? 

Nope, no errors.

> Also, if I supply you with some modifications to the tsify source - for additional logging - would you be able to re-run your build and provide me with the output? 

Yep - happy to.

> If so, I'll start looking into this. It is a strange one and no doubt frustrating for you.

Was already 10 levels deep in a yak shave - each level with similar frustration. Have lost voice due to expletives. Now considering career change :)

I have attached the working and non-working bundles in case they make more sense to you. The working bundle is created using the _incorrect_ case in the paths.

[bundle - working.js.txt](https://github.com/TypeStrong/tsify/files/736723/bundle.-.working.js.txt)
[bundle - not working.js.txt](https://github.com/TypeStrong/tsify/files/736722/bundle.-.not.working.js.txt)

**Comment by cartant** [comment]
> Have lost voice due to expletives.

I know how that feels.

Those bundles appear to be the same and both contain two modules, but the order is different. I suspect this is a Browserify thing that's related to the `--standalone` option. If it were related to this particular `tsify` issue, I'd expect an error. Lemme see what I can find out.

**Comment by cartant** [comment]
@duncanawoods I've had a look at those bundles and both bundles include modules for the `jasmine.d.ts` and `main.ts` files.

The former is included because it's specified as one of the Browserify entries. And it's empty because Tsify emits an empty module for `.d.ts` files - that's normal.

The problem with the non-working bundle is that the module chosen to be used for the `--standalone` option (that is, the `MyBundle` module) is the empty module that's associated with `jasmine.d.ts`. As to why that occurs, I do not know. And I don't particularly want to go digging through the Browserify source to figure it out.

You should be able to solve your problem by using a `tsconfig.json` file (which is par for the course for almost every TypeScript tool). Just create one in the same directory as your `package.json` and give it this content:

    {
        "compilerOptions": {
            "module": "commonjs",
            "moduleResolution": "node",
            "noImplicitAny": true,
            "suppressImplicitAnyIndexErrors": true,
            "target": "es5"
        },
        "files": [
            "..\folder1\jasmine.d.ts"
        ]
    }

Note that `..\folder1\jasmine.d.ts` is specified in the `files`. Tsify will find it, so it does not need to be specified as a Browserify entry:

    node node_modules/browserify/bin/cmd \
       "main.ts" --standalone MyBundle \
       -p [ tsify ] \
       -o "bundle.js"

With only a single entry, the `--standalone` should use the correct module for `MyBundle`.

There might be other solutions, but I don't use the `--standalone` often. Or, at all, really.

**Comment by cartant** [comment]
@TomKemperNL @duncanawoods Closing this as the case sensitivity bug should be fixed and the `--standalone` thing is likely a Browserify issue and has a workaround in any case.

**Comment by duncanawoods** [comment]
@cartant thanks, you have gone above and beyond

I have tried the config file but I get this error from inside tsify:

    λ node node_modules/browserify/bin/cmd "main.ts" --standalone MyBundle -p [ tsify ] -o "bundle.js"
    C:\Users\Duncan\Documents\TsifyTest\node_modules\error-ex\index.js:79
                    Object.defineProperty(this, 'stack', stackDescriptor);
                           ^
    
    TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
        at Function.defineProperty (<anonymous>)
        at new ErrorEXError (C:\Users\Duncan\Documents\TsifyTest\node_modules\error-ex\index.js:79:10)
        at module.exports (C:\Users\Duncan\Documents\TsifyTest\node_modules\parse-json\index.js:27:17)
        at parse (C:\Users\Duncan\Documents\TsifyTest\node_modules\tsconfig\dist\tsconfig.js:136:12)
        at Object.readFileSync     (C:\Users\Duncan\Documents\TsifyTest\node_modules\tsconfig\dist\tsconfig.js:128:12)
        at parseOptions (C:\Users\Duncan\Documents\TsifyTest\node_modules\tsify\lib\Tsifier.js:80:23)
        at new Tsifier (C:\Users\Duncan\Documents\TsifyTest\node_modules\tsify\lib\Tsifier.js:135:23)
        at tsify (C:\Users\Duncan\Documents\TsifyTest\node_modules\tsify\index.js:19:16)
        at Browserify.plugin (C:\Users\Duncan\Documents\TsifyTest\node_modules\browserify\index.js:362:9)
        at C:\Users\Duncan\Documents\TsifyTest\node_modules\browserify\bin\args.js:128:15

**Comment by cartant** [comment]
@duncanawoods Try it with forward slashes in the path: `"../folder1/jasmine.d.ts"`

**Comment by duncanawoods** [comment]
@cartant Yup, just fixed that unescaped backslash too :)

**Comment by duncanawoods** [comment]
@cartant in gratitude, please have this happier avatar and the need to use it
![happy-cartant](https://cloud.githubusercontent.com/assets/2480457/22394856/d12c260e-e523-11e6-81a8-1b6896cef56c.png)
